name: build

on:
  push:

jobs:
  build-native:
    name: build (${{ matrix.platform.name }})
    runs-on: ${{ matrix.platform.runner }}-latest

    strategy:
      matrix:
        platform:
          - { name: osx-x64,   runner: macos, arch: x86_64  }
          # - { name: osx-arm64, runner: macos, arch: arm64   }
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Create staging folder
        shell: bash
        run: |
          mkdir -p out/runtimes/osx-${{ matrix.platform.name }}/native

      - name: Build
        shell: bash
        working-directory: src
        run: |
          clang -O3 -arch ${{ matrix.platform.arch }} -dynamiclib support.c -o dist/runtimes/osx-${{ matrix.platform.name }}/native/libarmeilleure-jitsupport.dylib

      # - name: Upload artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: native-${{ matrix.platform.name }}
      #     path: dist/
